### ISSUE TITLE
TypeError: argument 'appname': 'bytes' object cannot be converted to 'PyString'

### ISSUE THREAD

**Issue by funicat1** [andfoy/pywinpty#473]
Whenever i try to use an pty, i get this error
```
Traceback (most recent call last):
  File "d:\test\main.py", line 8, in <module>
    process.spawn(br'C:\windows\system32\cmd.exe')
TypeError: argument 'appname': 'bytes' object cannot be converted to 'PyString'
```
And the code is really easy.
```python
from winpty import PTY

# Start a new winpty-agent process of size (cols, rows)
cols, rows = 80, 25
process = PTY(cols, rows)

# Spawn a new console process, e.g., CMD
process.spawn(br'C:\windows\system32\cmd.exe')

# Read console output (Unicode)
process.read()

# Write input to console (Unicode)
process.write(b'Text')

# Resize console size
new_cols, new_rows = 90, 30
process.set_size(new_cols, new_rows)

# Know if the process is alive
alive = process.isalive()

# End winpty-agent process
del process
```
And whenever i try to make it non-bytes
<details><summary>Details</summary>
<p>

process.spawn(br'C:\windows\system32\cmd.exe')

to

process.spawn(r'C:\windows\system32\cmd.exe')

</p>
</details> 
It returns a different error.

```
Traceback (most recent call last):
  File "d:\мой рабочий стол\transcmd\main.py", line 14, in <module>
    process.write(b'Text')
TypeError: argument 'to_write': 'bytes' object cannot be converted to 'PyString'
```

**Comment by funicat1** [comment]
Nevermind, just removed `b` from both functions. Fixed instantly
